name: Deploy React + .NET to Azure

on:
  push:
    branches:
      - main  # Altere para a branch correta

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: ğŸš€ Checkout do cÃ³digo
      uses: actions/checkout@v2

    - name: ğŸ“¦ Configurar .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x' # Ajuste para sua versÃ£o do .NET

    - name: ğŸ”¨ Build do Backend
      run: |
        cd GestaoEscala/Back/
        dotnet restore
        dotnet build --configuration Release
        dotnet publish -c Release -o ./publish

    - name: âš›ï¸ Build do Frontend (React)
      run: |
        cd front
        npm install
        npm run build
        mv build ../backend/publish/wwwroot # Move o build do React para o .NET

    - name: ğŸš€ Deploy para a Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: "GestaoEscala" # Nome do App Service na Azure
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: ./backend/publish
