name: Build and deploy ASP.Net Core app to Azure Web App - BackGestaoEscala

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Debug - Listar arquivos e diret√≥rios
        run: Get-ChildItem -Path . -Recurse

      - name: Configurar .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restaurar depend√™ncias
        run: dotnet restore Back/GestaoEscalaPermutas.sln

      - name: Compilar aplica√ß√£o
        run: dotnet build --configuration Release --no-restore Back/GestaoEscalaPermutas.sln

      - name: Publicar aplica√ß√£o
        run: dotnet publish -c Release -o ${{ github.workspace }}/publish Back/GestaoEscalaPermutas.sln

      - name: Upload dos artefatos para o job de deploy
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: 'https://backgestaoescala-a0hhfvg0f4h2d5hw.canadacentral-01.azurewebsites.net'
    
    steps:
      - name: Baixar os artefatos do job de build
        uses: actions/download-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/publish

      - name: Login_na_Azure  # üîπ Novo passo para autenticar antes do deploy
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AzureAppService_PublishProfile }}

      - name: Deploy para o Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'BackGestaoEscala'
          slot-name: 'Production'
          package: ${{ github.workspace }}/publish
